[package]
name = "CRB"
version = "0.1.0"
edition = "2024"

[features]
default = ["gpu-single"]
gpu-single = []

[dependencies]
anyhow = "1.0.102"
cfg-if = "1.0.4"
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
fitsio = "0.21.10"
fitsio-sys = "0.5.7"
indexmap = {version = "2.14.0", features = ["rayon", "serde"] }
io = "0.0.2"
itertools = "0.14.0"
lazy_static = "1.5.0"
log = "0.4.29"
marlu = { version = "0.17.0", features = ["serde"] }
mwalib = "2.0.4"
ndarray = {version = "0.17.2", features = ["rayon"] }
ndarray-linalg = { version = "0.18.1", features = ["openblas-system"] }
num-complex = "0.4.6"
num-traits = "0.2.19"
opencl3 = "0.12.3"
physical_constants = "0.5.0"
rayon = "1.12.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
strum = "0.28.0"
strum_macros = "0.28.0"
thiserror = "2.0.18"
toml = "1.1.2"
vec1 = { version = "1.12.1", features = ["serde"] }
